site_name: opti_fit
site_url: https://RichardOberdieck.github.io/opti_fit/
repo_url: https://github.com/RichardOberdieck/opti_fit
repo_name: opti_fit

theme:
  name: "material"
  features:
    - content.code.copy
  palette: 

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode



nav:
  - Home: 'index.md'
  - Definitions: 'definitions.md'
  - Dataset: 'the-dataset.md'
  - Simple Model: 'simple-model.md'
  - Algorithm Combination: 'algorithm-combination.md'
  - Relaxing True Positive Requirements: 'relax-the-true-positive-requirement.md'
  - Solver Comparison: 'solver-comparisons.md'
  - Results: 'results.md'
  - Future Ideas: 'future-ideas.md'

plugins:
  - search
  - mkdocstrings
  - plotly

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: plotly
          class: mkdocs-plotly
          format: !!python/name:mkdocs_plotly_plugin.fences.fence_plotly

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
