name: Deploy documentation

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install hatch
        run: python -m pip install hatch
      - name: Deploy docs
        run: hatch run docs:deploy
